theme: jekyll-theme-hacker
title: Adam Miszczak
email: adammiszczak1@gmail.com
description: Blog about SEO, Front-end and many others
url: https://adammiszczak.github.io/
twitter_username: AdamMiszczak
github_username: AdamMiszczak
permalink: /:categories/:title
paginate: 4
paginate_path: posts/page:num/
sass:
    sass_dir: _sass
