theme: jekyll-theme-hacker
title: My Jekyll Blog
email: adammiszczak1@gmail.com
description: Blog about SEO, Front-end and many others
url: https://adammiszczak.github.io/
twitter_username: AdamMiszczak
github_username: AdamMiszczak